language: go
go:
 - 1.4.2
 - 1.7
 - 1.11
 - 1.15
 - tip

script:
 - go test -v ./...

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -v -coverprofile=coverage.txt -covermode=count github.com/jcuga/golongpoll
  - go test -v github.com/jcuga/golongpoll/go-client/glpclient

after_success:
  - bash <(curl -s https://codecov.io/bash)
