language: go
go:
 - 1.9
 - 1.11
 - 1.16

script:
 - go test -v ./...

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet ./...
  - go test -v -coverprofile=coverage.txt -covermode=count github.com/jcuga/golongpoll
  - go test -v github.com/jcuga/golongpoll/client
  - go build examples/chatbot/chatbot.go
  - go build examples/filepersist/filepersist.go
  - go build examples/stressor/server/main.go
  - go build examples/stressor/client/main.go
  - go build examples/authentication/auth.go
  - go build examples/microchat/microchat.go

after_success:
  - bash <(curl -s https://codecov.io/bash)
